# Site settings
title: "CS371p Fall 2015: Juan Villegas"
email: j_villegas5@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  My blog for CS 371 OOP!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  jjv722

# Build settings
markdown: kramdown
